export const GET_GALLERY = 'GET_GALLERY';
export const ADD_GALLERY = 'ADD_GALLERY';
export const DELETE_GALLERY = 'DELETE_GALLERY';
export const SET_LOADING = 'SET_LOADING';
export const GALLERY_ERROR = 'GALLERY_ERROR';